name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # master 브랜치에 푸시될 때만 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js 설치
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. 의존성 설치 및 빌드
      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Debug workspace
        run: |
          pwd
          ls -la

      - name: Debug build directory
        run: |
          ls -la ./dist

  deploy:
    needs: build  # build가 완료된 후 실행
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 빌드 결과물을 gh-pages 브랜치로 배포
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # 빌드 결과물 디렉토리
